name: Build and push docker image
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "App Name (e.g. fas-rstudio-general)"
        required: true
        default: ""
  repository_dispatch:
    types: [trigger-docker-build]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Inspect github event
        run: |
          echo "Github Event: ${{ toJson(github.event) }}"
      - name: Set environment variable for APP_NAME from workflow_dispatch or repository_dispatch
        run: |
          APP_NAME="${{ github.event.inputs.app_name }}";
          if [ -z "$APP_NAME" ]; then
            APP_NAME="${{ github.event.client_payload.app_name }}";
          fi;
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV;
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set environment variables for image tagging
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        if: ${{ env.APP_NAME }}
        with:
          file: "./apps/${{ env.APP_NAME }}/Dockerfile"
          push: true
          tags: |
            harvardat/${{ env.APP_NAME }}:${{ env.SHORT_SHA }}
            harvardat/${{ env.APP_NAME }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
