name: Docker Build
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "App Name (e.g. fas-rstudio-general)"
        required: true
        default: ""

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set APP_NAME env variable
        run: |
           APP_NAME="${{ github.event.inputs.app_name }}";
           echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV;

      - name: Ensure APP_NAME is defined
        if: "!env.APP_NAME"
        run: exit 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Configure docker image metadata
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: harvardat/${{ env.APP_NAME }}
          tags: |
            type=ref,event=branch
            type=sha

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: "./apps/${{ env.APP_NAME }}"
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
